# Generated by Django 5.2.5 on 2025-09-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('national_alignment', models.CharField(blank=True, max_length=255, null=True)),
                ('focus_areas', models.TextField(help_text='Comma-separated list of domains')),
                ('phases', models.TextField(help_text='Comma-separated list of phases')),
            ],
        ),
    ]
