# Generated by Django 5.2.1 on 2025-09-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('partner_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_type', models.CharField(max_length=100)),
                ('capabilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('nature_of_project', models.CharField(max_length=100, blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('innovation_focus', models.CharField(max_length=255, blank=True, null=True)),
                ('prototype_stage', models.CharField(max_length=100, blank=True, null=True)),
                ('testing_requirements', models.TextField(blank=True, null=True)),
                ('commercialization_plan', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.facility')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.facility')),
            ],
        ),
    ]
