# Generated by Django 5.2.1 on 2025-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_facility_equipment_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
