# Generated by Django 5.2.1 on 2025-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facility_facility_id_program_program_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='partner_organization',
            field=models.CharField(blank=True, choices=[('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], max_length=200, null=True),
        ),
    ]
