# Generated by Django 5.2.1 on 2025-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_facility_partner_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='capabilities',
            field=models.CharField(choices=[('CNC', 'CNC'), ('PCB fabrication', 'PCB fabrication'), ('materials testing', 'materials testing')], max_length=255),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Workshop', 'Workshop'), ('Testing Center', 'Testing Center')], max_length=100),
        ),
    ]
