# Generated by Django 5.2.1 on 2025-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_facility_capabilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='focus_areas',
            field=models.CharField(choices=[('IoT', 'IoT'), ('automation', 'automation'), ('renewable energy', 'renewable energy')], help_text='Comma-separated list of domains', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='national_alignment',
            field=models.CharField(blank=True, choices=[('NDPIII', 'NDPIII'), ('Roadmap', 'Roadmap'), ('4IR goals', '4IR goals')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='phases',
            field=models.CharField(choices=[('Cross-Skilling', 'Cross-Skilling'), ('Collaboration', 'Collaboration'), ('Technical Skills', 'Technical Skills'), ('Prototyping', 'Prototyping'), ('Commercialization', 'Commercialization')], help_text='Comma-separated list of phases', max_length=255),
        ),
    ]
