# Generated by Django 4.2.23 on 2025-09-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_program_focus_areas_and_more'),
    ]

    operations = [
    ]
