# Generated by Django 5.1.1 on 2025-09-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_program_focus_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('CS', 'CS'), ('SE', 'SE'), ('Engineering', 'Engineering'), ('Other', 'Other')], max_length=100)),
                ('specialization', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Business', 'Business')], max_length=100)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='capabilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='support_phase',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Prototyping', 'Prototyping'), ('Testing', 'Testing'), ('Commercialization', 'Commercialization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='usage_domain',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('IoT', 'IoT')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Machining', 'Machining'), ('Testing', 'Testing'), ('Training', 'Training')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Integration', 'Integration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='nature_of_project',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Prototype', 'Prototype'), ('Applied', 'Applied')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prototype_stage',
            field=models.CharField(blank=True, choices=[('Concept', 'Concept'), ('Prototype', 'Prototype'), ('MVP', 'MVP'), ('Market Launch', 'Market Launch')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('artifact_link', models.URLField(blank=True, null=True)),
                ('outcome_type', models.CharField(choices=[('CAD', 'CAD'), ('PCB', 'PCB'), ('Prototype', 'Prototype'), ('Report', 'Report'), ('Business Plan', 'Business Plan')], max_length=100)),
                ('quality_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('commercialization_status', models.CharField(blank=True, choices=[('Demoed', 'Demoed'), ('Market Linked', 'Market Linked'), ('Launched', 'Launched')], max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_project', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Contributor', 'Contributor')], max_length=100)),
                ('skill_role', models.CharField(choices=[('Developer', 'Developer'), ('Engineer', 'Engineer'), ('Designer', 'Designer'), ('Business Lead', 'Business Lead')], max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='core.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'participant')},
            },
        ),
    ]
