# Generated by Django 4.2.23 on 2025-09-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250902_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('full_name', models.CharField(default='Unknown Participant', max_length=200)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('CS', 'CS'), ('SE', 'SE'), ('Engineering', 'Engineering'), ('Other', 'Other')], default='Other', max_length=100)),
                ('specialization', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Business', 'Business')], default='Software', max_length=100)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UniPod', 'UniPod'), ('UIRI', 'UIRI'), ('Lwera', 'Lwera')], default='SCIT', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='capabilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='support_phase',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Prototyping', 'Prototyping'), ('Testing', 'Testing'), ('Commercialization', 'Commercialization')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='usage_domain',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('IoT', 'IoT')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='commercialization_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Project description'),
        ),
        migrations.AddField(
            model_name='project',
            name='innovation_focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nature_of_project',
            field=models.CharField(choices=[('Research', 'Research'), ('Prototype', 'Prototype'), ('Applied', 'Applied')], default='Research', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.program'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prototype_stage',
            field=models.CharField(blank=True, choices=[('Concept', 'Concept'), ('Prototype', 'Prototype'), ('MVP', 'MVP'), ('Market Launch', 'Market Launch')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='testing_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='New Project', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('Machining', 'Machining'), ('Testing', 'Testing'), ('Training', 'Training')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Integration', 'Integration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='project',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='service',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.facility'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('title', models.CharField(default='New Outcome', max_length=200)),
                ('description', models.TextField(default='Outcome description')),
                ('artifact_link', models.URLField(blank=True, null=True)),
                ('outcome_type', models.CharField(choices=[('CAD', 'CAD'), ('PCB', 'PCB'), ('Prototype', 'Prototype'), ('Report', 'Report'), ('Business Plan', 'Business Plan')], default='Report', max_length=100)),
                ('quality_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('commercialization_status', models.CharField(blank=True, choices=[('Demoed', 'Demoed'), ('Market Linked', 'Market Linked'), ('Launched', 'Launched')], max_length=100, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_project', models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Contributor', 'Contributor')], default='Student', max_length=100)),
                ('skill_role', models.CharField(choices=[('Developer', 'Developer'), ('Engineer', 'Engineer'), ('Designer', 'Designer'), ('Business Lead', 'Business Lead')], default='Developer', max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='core.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'participant')},
            },
        ),
    ]
