# Generated by Django 5.2.1 on 2025-09-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_participant_remove_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='artifact_file',
            field=models.FileField(blank=True, null=True, upload_to='outcomes/'),
        ),
    ]
